proxy:
    secretToken: c65b057a6ba96ee5562f4ea7d78f949d353908f52601c50c29223dd30166ccf1
auth:
  admin:
    users:
      - ak27
      - vk6
      - svd
  type: ldap
  ldap:
    server:
      address: ldap-ro.internal.sanger.ac.uk
    dn:
      templates:
        - 'uid={username},ou=people,dc=sanger,dc=ac,dc=uk'
ingress:
    enabled: false
    hosts:
     - jupyter.cellgeni.sanger.ac.uk
     - jupyter.cellgeni.internal.sanger.ac.uk

singleuser:
  defaultUrl: "/lab"
  memory:
    limit: 16G
    guarantee: 8G
  cpu:
    limit: 4
    guarantee: 2
  image:
    name: quay.io/cellgeni/cellgeni-jupyter
    tag: v0.2.2
  lifecycleHooks:
    postStart:
      exec:
        command: ["bash", "/poststart.sh"]
